testing:
  sampling:
    measurements_count: 20
    total_duration_ms: null
    sampling_frequency_ms: 100
    sampling_frequency_min_val: 25

ammeters:
  greenlee:
    port: 5000
    command: "MEASURE_GREENLEE -get_measurement"
    expected_range:
      min: 0.01
      max: 100.0

analysis:
  statistical_metrics:
  visualization:
    enabled: true
    plot_types: []

result_management: {}